### ISSUE TITLE
mechanism to backup list of packages and their configurations 

### ISSUE THREAD

**Issue by musm** [appget/appget#11]
I'd like to request a feature where the list off appget installed packages and their installation configurations can be backup up automatically and also a mechanism where this backup can be automatically installed on new computers.

Thanks.

**Comment by kayone** [comment]
this is something that has been planned for a long time. something similar to package.json or packages.config

could you elaborate what you mean by "their installation configuration"?

**Comment by kayone** [comment]
closing in favor of #27
