### ISSUE TITLE
Installing AppGet in different directory

### ISSUE THREAD

**Issue by quantuumsnot** [appget/appget#13]
The installer went straight through my eyes and installed in C:\ProgramData while I was waiting to pick a custom directory

**Comment by kayone** [comment]
Any reason you would want to change the directory? The main reason we use `C:\program data` is because it is accessible/writeable by all users, which means appget can update itself without a need for administrator privileges.

**Comment by quantuumsnot** [comment]
Yes, polluting the SSDs with constant writing makes them more fragile especially on home computers. And using symlinking as workaround is not good in some cases like having remote symlinks for a couple of identical PCs over the local network

**Comment by kayone** [comment]
to be honest, I don't think conserving SSD's write cycle enough reasons to cause update issue. specially when we are talking about the minor number of writes caused by appget itself.

**Comment by quantuumsnot** [comment]
Yes, but having an option to enforce a different working directory with full access is enough for users like me who don't wanna wear their SSDs too fast

**Comment by kayone** [comment]
I really don't see how moving appget to a different drive would reduce any meaningful amount of wear from your SSD.

where appget is installed doesn't have any effect on where the apps you install with it are installed. So are we talking about just appget itself? which is 5MB of writes to your SSD every few weeks when an update is released?

**Comment by quantuumsnot** [comment]
Ok, let start from the beginning. Do the authors of AppGet tested all applications to see where they are installed and where they actually write on drive?

**Comment by kayone** [comment]
AppGet has no control over where the apps install themselves, Appget will run the installers in silent mode. if you want control over where the apps install themselves you can run the installer in interactive mode which lets you run through the installer manually. for example `appget install vlc -i`

**Comment by quantuumsnot** [comment]
Well, this works

**Comment by kayone** [comment]
@quantuumsnot I think what you were actually interested in was https://github.com/appget/appget/issues/14
