### ISSUE TITLE
Appget List Packages Feature Request

### ISSUE THREAD

**Issue by gitjeff2** [appget/appget#22]
When managing a large number of packages as an administrator it is often necessary to check and see if an existing package is installed either by package name or package name and version number. On Linux this can be accomplished via `apt list --installed` or `yum list all`, etc. On Windows, Chocolatey supports this with `choco list --local-only` (I think).

Ideally, the output would lend itself well to being searched by `grep` or `Select-String` or redirected to file with one line per package.

**Comment by kayone** [comment]
Done. See https://docs.appget.net/commands/#list
