### ISSUE TITLE
[Feature Request] ReactOS Support

### ISSUE THREAD

**Issue by gitjeff2** [appget/appget#23]
First off, *very nice* project.

You may or may not know this but there is an open source reimplimentation of Microsoft Windows called [ReactOS](https://reactos.org). Making special effort to get `appget` working under ReactOS might gain your project some visibility; it certainly deserves some.

The ReactOS project is currently in a late public alpha and is reasonably stable. I mention this because the project has long had its eye on building or adopting a package manager. It currently has a GUI-only stand-in for an [eventual replacement package manager](https://reactos.org/wiki/ReactOS_Update#Package_Management).

## AppGet Testing Under ReactOS Thus Far
* Testing was performed under ReactOS 0.4.10 in a VirtualBox VM.
* Attempts to execute the installer failed with "Your operating system version is not supported" (or similar) error.
* Enabling compatibility mode and setting the reported OS version to Windows 7 fails indicating the lack of an appropriate service pack.
* You don't have build instructions documented (and I'm not super familiar with C#) so I wasn't able to build appget with the OS checks disabled just to see how far I could get.

I suspect the root cause is the fact that ReactOS reports its version kernel version as `5.2` instead of `6.0` or greater. The last post on [this thread](https://reactos.org/forum/viewtopic.php?t=1401) describes the canonical way to detect ReactOS is present instead of MS Windows. That post is a bit old, so these instructions could be dated.

**Comment by kayone** [comment]
So I've some time trying to get ReactOS running on a VM but can't get the network drivers to load correctly in hyper-v.

Anyways, most of the issues you've posted seem related to the installer system requirements, I would recommend copying the appget files from a windows system `C:\ProgramData\AppGet\bin\` to a reactOS system and trying to run some of the commands and see what you get.


just keep in mind, whether or not we decide to support ReactOS really depends on how well it supports the packages in our repository.

**Comment by gitjeff2** [comment]
> So I've some time trying to get ReactOS running on a VM but can't get the network drivers to load correctly in hyper-v.

Yeah, you have to set the NIC to PCnet-FAST III to get it on the wire. [ReactOS release 0.4.12](https://reactos.org/wiki/Community_Changelog-0.4.12) (which isn't out yet) adds support for Intel E1000 NICs, the default for most hypervisors.

> just keep in mind, whether or not we decide to support ReactOS really depends on how well it supports the packages in our repository.

My mistake. I didn't realize that ReactOS lacked support for Dot NET out of the box; expected Mono (open source Dot NET) to "just work". I'll keep playing with appget on ReactOS, just to see if I can get it to work. But, you can close this. 

If my testing exposes any appget bugs, I'll open a separate issue.
