### ISSUE TITLE
"AppGet update failed. Sequence contains more than one matching element"

### ISSUE THREAD

**Issue by priyadarshan** [appget/appget#25]
Today I updated all my installs from AppGet, and I started getting message:

```
AppGet update failed. Sequence contains more than one matching element
```
![image](https://user-images.githubusercontent.com/1652143/52901908-09fabd80-320a-11e9-809c-d9b4ca98474e.png)

I have the latest release.

Thank you for AppGet. I like it very much. It suits my use-case much better than chocolatey or scoop.

**Comment by gitjeff2** [comment]
I can confirm that I'm having the same issue. My `appget` version is very slightly behind that of the OP. My system is a *very* fresh install of Windows 10 that is fully patched.

```
PS C:\> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
PS C:\> appget --version
AppGet 0.6.31.0
AppGet update failed. Sequence contains more than one matching element
PS C:\>
```

This is the same version  of `appget` that I deployed packages with just a few days ago. So, I don't think this is an issue with the `appget` binary itself. More probably, this is an issue with an Internet resource that appget points to. That said, the application shouldn't be touching the network when simply invoking `--version`.

Maybe there is something wrong with the manifests repository?

**Comment by albertdev** [comment]
The problem is here:

https://github.com/appget/appget/blob/3efe9139ed1009c5d7d4df6a564f4155115bd024/src/AppGet/Github/Releases/GitHubReleaseClient.cs#L35

Apparently `appget` checks the latest version each time you run it. Because the [latest release](https://github.com/appget/appget/releases/tag/0.6.37) happens to contain a whole bunch of files (including 2 extra executables) rather than a single installer exe, the linked code goes crazy and triggers that error.

Of course, that latest release isn't correct but the code should be made to fail gracefully.

**Comment by gitjeff2** [comment]
> Apparently `appget` checks the latest version each time you run it… the code should be made to fail gracefully.

In the event of some weird conflict the application should continue to work normally, give or take a warning/error related to the conflict at hand.

Checking for updates should *not* occur every time the `appget` command is invoked. Ideally, `appget` should have it's own entry in the repository and *only* check for updates at the same time as other packages under its control. This is standard behavior for other package managers, including the likes of `yum` and `apt-get`.

**Comment by kayone** [comment]
you guys are fast!

- What happened? the deploy process pushed too many files to GitHub releases which confused/broke the client.
- Is it fixed? yeah, I removed all the extra files. all is well again.
- Why not handle this better? well, an update failure doesn't affect the functionality of the app. it just logs the error and continues as usual, but it looks like there are some messaging improvements to be had :)
- Why check for update every time? I know, we are overdoing it. it's a leftover from when appget wasn't as stable as it is now, and we wanted to push fixes to testers asap. we'll take a look at improving that.

**Comment by priyadarshan** [comment]
Thank you so much for fixing it, it works perfectly now.

I am so grateful for AppGet. Thank you.
