### ISSUE TITLE
Cannot compile source code

### ISSUE THREAD

**Issue by m4ss1m0g** [appget/appget#29]
I downloaded source code but I cannot recompile app.

> The tag 'ModernWindow' does not exist in XML namespace 'https://github.com/bakx/mui'. Line 1 Position 24. AppGet.Gui ShellView.xaml   

> XDG0008	The name "CaliburnBootstrapper" does not exist in the namespace "clr-namespace:AppGet.Gui.Framework".	AppGet.Gui	App.xaml	1	

> XDG0008	The name "ModernWindow" does not exist in the namespace "https://github.com/bakx/mui".	AppGet.Gui	ShellView.xaml	1	

> XLS0414	The type 'controls:ModernWindow' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	AppGet.Gui	ShellView.xaml	1	

Also the external projects

- ModernUI
- ModernUI.App

Are unavailable

**Comment by kayone** [comment]
you need to pull the project with it's submodules, 

`git pull --recurse-submodules`

see: https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules

**Comment by m4ss1m0g** [comment]
It worked ! Thanks.
