### ISSUE TITLE
AppGet Installs Fail When Windows 10 Controlled Folder Access Protection is Enabled

### ISSUE THREAD

**Issue by gitjeff2** [appget/appget#30]
[Windows Defender](https://en.wikipedia.org/wiki/Windows_Defender) now has feature called "Controlled Folder Access" which is intended to inhibit [ransomware attacks](https://en.wikipedia.org/wiki/Ransomware). Attempting to `C:\> appget install [some_package]` fails when this feature is enabled. This feature was added or substantially updated as part of the Windows 10 October 2018 update.

There are instructions for giving an application permission to access Controlled Folders using the GUI, here: <https://www.windowscentral.com/how-allow-blocked-apps-ransomware-protection-windows-10-october-2018-update>. 

I'm not sure what API calls are required to automate this. Even if `appget` gives itself permission to access controlled folders, I'm not sure if child (active installer) processes will inherit this permission.

**Comment by kayone** [comment]
So I've tried installing a bunch of different apps while enabling controlled folder and they all went through as expected.

Did you happen to add any custom folders to the list of protected folders?
Which packages specifically were you trying to install that caused issue?

**Comment by gitjeff2** [comment]
That's odd...

No, I didn't add any custom folders. I was very specifically using the `libreoffice` package. I was installing and uninstalling (with reboots) to test LibreOffice installer switches prior to submitting my pull request. Try that package with controlled folder access protection enabled and see if you get a different result.

If it happens again, is there a log file I can pull and associate with this issue?

**Comment by kayone** [comment]
can you run the installer with `-v` option and just paste the output. 

`appget install libreoffice -v`

**Comment by kayone** [comment]
closing this for now since there hasn't been a response for a while.
