### ISSUE TITLE
Unsupported Windows version

### ISSUE THREAD

**Issue by FuSoftware** [appget/appget#37]
I'm currently unable to install AppGet, as it says I run an unsupported version of Windows : Windows 7 Enterprise SP1 (64 bits)

Tried on 0.6.51, 0.6.50, 0.6.47

I couldn't find the list of supported OSes, which OS are supported ?

**Comment by FuSoftware** [comment]
Nevermind, it was a leftover from using the XP SP3 compatibility tool, looks like it requires Win7 to be installed

**Comment by kayone** [comment]
Yes, we don't support Windows XP/Vista
