### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jmartins1** [appget/appget#44]
Guys love AppGet nice job!

If I can tell you how I use it and a feature that would be pretty awesome.

I deployed AppGet to my lab computers. As you know keeping apps patched is important. Using PDQ Deploy I wrote a simple script that tells each computer to run AppGet to check/update select applications. Here's a snip-it of the batch file.

"C:\ProgramData\AppGet\appget.exe" update 7zip
"C:\ProgramData\AppGet\appget.exe" update adobe-reader
Etc

This works great! All my apps remain up-to-date!

The issue are apps that are proprietary and can't be added to the AppGet repository.

I would love to see a option to would to tell AppGet to use a different directory for the repository.

Example"

"C:\ProgramData\AppGet\appget.exe" update \\FileShare\7zip.msi
"C:\ProgramData\AppGet\appget.exe" update adobe-reader

Thanks for your considerations

Great job!

**Comment by kayone** [comment]
This is something that should be covered under private repositories. We've started work on it, but was temporary put on hold for some other higher priority core stuff. We should be able to get back to it soon.
