### ISSUE TITLE
500:InternalServerError

### ISSUE THREAD

**Issue by dosoft** [appget/appget#49]
After clean installation `appget list -v` displays the following error message:

```
Starting command [list]
Getting list of installed application
Getting list of matching packages...
Found 0.8.19 AppGet releases
Request to https://novo.appget.net/updates failed. 500:InternalServerError
AppGet update status:  Current: 1.0.0.0    Latest: 0.8.19
```

**Comment by kayone** [comment]
Sorry about that, it should be fixed now.

**Comment by dosoft** [comment]
> Sorry about that, it should be fixed now.

Still doesn't work for me.

**Comment by kayone** [comment]
I've added more logging to the server, could you try again.

**Comment by dosoft** [comment]
I just run it again and the output is the same.

**Comment by kayone** [comment]
😞 Could you please try again. I wouldn't bug you so much about this, but I can't really reproduce the issue locally. I've added more logging so hopefully, I can finally figure out what is causing the issue.

**Comment by dosoft** [comment]
No probs, I have run this command again. Feel free to contact me by email (on the profile) if you need more details or to run something for diagnostics on my side.

**Comment by kayone** [comment]
I'm pretty sure I've fixed the issue :) give it a go and let me know.

**Comment by dosoft** [comment]
🍾

```
...
Total Applications: 21   Updates Available: 9

Run 'appget update-all' to apply all updates.
```

**Comment by kayone** [comment]
Thanks a lot for your help tracking down the issue.
