### ISSUE TITLE
appget list not working

### ISSUE THREAD

**Issue by npearson72** [appget/appget#53]
Seems appget is not tracking installed applications. I've tried both `àppget list` and `appget outdated -v` and both generate only a small list of the applications I have installed.

Some examples of what does not appear:

1password
geforce-experience
chrome
twitch
battlenet
autohotkey
dropbox

The only apps that do appear for me are:

standard-notes
appget
ccleaner

---

Are there any instructions on how I can better report this to help troubleshoot?

**Comment by kayone** [comment]
It goes back to this issue, https://github.com/appget/appget/issues/15

**Comment by npearson72** [comment]
Closing this in anticipation of #15
