### ISSUE TITLE
API for AppGet packages

### ISSUE THREAD

**Issue by JudahGabriel** [appget/appget#57]
Feature request: an API to query list of packages on AppGet.

I'm building some experimental software atop AppGet. It would be useful to be able to programmatically query for packages over HTTP.

**Comment by kayone** [comment]
It's not documented since it might change but for now, would this help, 

`https://nex.appget.net/packages?q=firefox`

**Comment by JudahGabriel** [comment]
That's great, I really appreciate that.

After I posted this, I realized I could probably query [AppGet.packages on GitHub](https://github.com/appget/appget.packages/tree/master/manifests) via the [GitHub API](https://developer.github.com/v3/). Do you think that's feasible?

**Comment by kayone** [comment]
It really depends on what you want to do, if you want "Search" then the best would be to use the API since it actually does a smart text search.

If you want a dump of all packages or know the package ID and just want the manifest then you can go the github route.
