### ISSUE TITLE
Allow for optional way to change the reference installation folder

### ISSUE THREAD

**Issue by Siliconrob** [appget/appget#60]
https://github.com/appget/appget/blob/5b4c5463d85a7809638d876b07f5501271f32554/src/AppGet/HostSystem/PathResolver.cs#L28

This is a good default, but it would be nice if I could set this to a command line option override to install location.

**Comment by kayone** [comment]
Sounds pretty reasonable, we have some infra work to do for allowing and managing config settings. once that is done we can make this and a bunch of other things configurable.
