### ISSUE TITLE
Cannot sign-up with email on https://appget.net/

### ISSUE THREAD

**Issue by igor-toporet** [appget/appget#7]
"Network Error" is displayed underneath the email field.

![appget-signup-network-error](https://user-images.githubusercontent.com/758320/45389279-5b09e400-b5d0-11e8-8cbd-9e3848f47811.png)

**Comment by kayone** [comment]
should be fixed :)

**Comment by igor-toporet** [comment]
Thank you Keivan! Confirmed :)
