### ISSUE TITLE
Intellij package outdated check is not working

### ISSUE THREAD

**Issue by ekot1** [appget/appget#9]
It looks like intellij uses different version formats in file name and when registering in Windows, so it always shows up as outdated even when updated to latest version. It shows up as following when I run 
appget outdated
```
| Package ID | Installed Version | Available Version |
|------------|-------------------|-------------------|
| intellij   | 182.4505.22       | 2018.2.4          |
```

**Comment by kayone** [comment]
I've updated our scanner to be smarter about jetbrains installers, please let me know if that has fixed your issue.

https://github.com/appget/appget.packages/commit/12df99c0c24c3825ae4a7e8f791abb95aac8f915

**Comment by ekot1** [comment]
Thank you, it does not show as outdated anymore.
